  #programa para recetas
print('+++Receta cocina')
nombre_plato= input('Ingrese el nombre de la receta: ')
ingredientes = input('Ingrese los ingredientes: ')
tiempo= int(input('Tiempo de preparacion en minutos: '))
dificultad = input('Ingresa nivel de dificultad (Facil,Normal,Dificil)')
print('-----------\n')
print(f'nombre de la receta: {nombre_plato}')
print(f'Ingredientes: {ingredientes}')
print(f'Tiempo de preparacion: {tiempo}')
print(f'Dificultad: {dificultad}')
